
env:
  browser: true
  node: true
  es6: true
extends:
  - 'airbnb'
rules:
  arrow-body-style: off
  arrow-parens: 0
  class-methods-use-this: 1
  comma-dangle: 0
  dot-notation: 0
  import/extensions: 0
  import/first: 0
  import/imports-first: 0
  import/newline-after-import: 1
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/prefer-default-export: 1
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/media-has-caption: 0
  max-len: 0
  no-alert: 1
  no-console: 1
  no-unused-vars: 1
  no-useless-escape: 0
  quotes: 0
  react/jsx-filename-extension: 0
  react/prefer-stateless-function: 1
  react/require-default-props: 0
  semi: 1
  spaced-comment: 1
  space-before-function-paren: 0
